# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ros_can_interface/master_navigationMessage.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class master_navigationMessage(genpy.Message):
  _md5sum = "fe1a2421738fe61ce953bf0c9b6e4f00"
  _type = "ros_can_interface/master_navigationMessage"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 nav_targetX
float32 nav_targetY
float32 nav_targetAngle
bool nav_isForward
"""
  __slots__ = ['nav_targetX','nav_targetY','nav_targetAngle','nav_isForward']
  _slot_types = ['float32','float32','float32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       nav_targetX,nav_targetY,nav_targetAngle,nav_isForward

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(master_navigationMessage, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.nav_targetX is None:
        self.nav_targetX = 0.
      if self.nav_targetY is None:
        self.nav_targetY = 0.
      if self.nav_targetAngle is None:
        self.nav_targetAngle = 0.
      if self.nav_isForward is None:
        self.nav_isForward = False
    else:
      self.nav_targetX = 0.
      self.nav_targetY = 0.
      self.nav_targetAngle = 0.
      self.nav_isForward = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3fB().pack(_x.nav_targetX, _x.nav_targetY, _x.nav_targetAngle, _x.nav_isForward))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 13
      (_x.nav_targetX, _x.nav_targetY, _x.nav_targetAngle, _x.nav_isForward,) = _get_struct_3fB().unpack(str[start:end])
      self.nav_isForward = bool(self.nav_isForward)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3fB().pack(_x.nav_targetX, _x.nav_targetY, _x.nav_targetAngle, _x.nav_isForward))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 13
      (_x.nav_targetX, _x.nav_targetY, _x.nav_targetAngle, _x.nav_isForward,) = _get_struct_3fB().unpack(str[start:end])
      self.nav_isForward = bool(self.nav_isForward)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3fB = None
def _get_struct_3fB():
    global _struct_3fB
    if _struct_3fB is None:
        _struct_3fB = struct.Struct("<3fB")
    return _struct_3fB
