# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ros_can_interface/navigator_navigationMessage.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class navigator_navigationMessage(genpy.Message):
  _md5sum = "90176a0f60fd26d08c0aaca4ecb268df"
  _type = "ros_can_interface/navigator_navigationMessage"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 nav_currentX
float32 nav_currentY
float32 nav_currentAngle
int8 nav_currentState"""
  __slots__ = ['nav_currentX','nav_currentY','nav_currentAngle','nav_currentState']
  _slot_types = ['float32','float32','float32','int8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       nav_currentX,nav_currentY,nav_currentAngle,nav_currentState

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(navigator_navigationMessage, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.nav_currentX is None:
        self.nav_currentX = 0.
      if self.nav_currentY is None:
        self.nav_currentY = 0.
      if self.nav_currentAngle is None:
        self.nav_currentAngle = 0.
      if self.nav_currentState is None:
        self.nav_currentState = 0
    else:
      self.nav_currentX = 0.
      self.nav_currentY = 0.
      self.nav_currentAngle = 0.
      self.nav_currentState = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3fb().pack(_x.nav_currentX, _x.nav_currentY, _x.nav_currentAngle, _x.nav_currentState))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 13
      (_x.nav_currentX, _x.nav_currentY, _x.nav_currentAngle, _x.nav_currentState,) = _get_struct_3fb().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3fb().pack(_x.nav_currentX, _x.nav_currentY, _x.nav_currentAngle, _x.nav_currentState))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 13
      (_x.nav_currentX, _x.nav_currentY, _x.nav_currentAngle, _x.nav_currentState,) = _get_struct_3fb().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3fb = None
def _get_struct_3fb():
    global _struct_3fb
    if _struct_3fb is None:
        _struct_3fb = struct.Struct("<3fb")
    return _struct_3fb
