// Generated by gencpp from file path_planner/PathPlan.msg
// DO NOT EDIT!


#ifndef PATH_PLANNER_MESSAGE_PATHPLAN_H
#define PATH_PLANNER_MESSAGE_PATHPLAN_H

#include <ros/service_traits.h>


#include <path_planner/PathPlanRequest.h>
#include <path_planner/PathPlanResponse.h>


namespace path_planner
{

struct PathPlan
{

typedef PathPlanRequest Request;
typedef PathPlanResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PathPlan
} // namespace path_planner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::path_planner::PathPlan > {
  static const char* value()
  {
    return "a9186ff1c0833e5c6cc2915c1b9610f7";
  }

  static const char* value(const ::path_planner::PathPlan&) { return value(); }
};

template<>
struct DataType< ::path_planner::PathPlan > {
  static const char* value()
  {
    return "path_planner/PathPlan";
  }

  static const char* value(const ::path_planner::PathPlan&) { return value(); }
};


// service_traits::MD5Sum< ::path_planner::PathPlanRequest> should match
// service_traits::MD5Sum< ::path_planner::PathPlan >
template<>
struct MD5Sum< ::path_planner::PathPlanRequest>
{
  static const char* value()
  {
    return MD5Sum< ::path_planner::PathPlan >::value();
  }
  static const char* value(const ::path_planner::PathPlanRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_planner::PathPlanRequest> should match
// service_traits::DataType< ::path_planner::PathPlan >
template<>
struct DataType< ::path_planner::PathPlanRequest>
{
  static const char* value()
  {
    return DataType< ::path_planner::PathPlan >::value();
  }
  static const char* value(const ::path_planner::PathPlanRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::path_planner::PathPlanResponse> should match
// service_traits::MD5Sum< ::path_planner::PathPlan >
template<>
struct MD5Sum< ::path_planner::PathPlanResponse>
{
  static const char* value()
  {
    return MD5Sum< ::path_planner::PathPlan >::value();
  }
  static const char* value(const ::path_planner::PathPlanResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_planner::PathPlanResponse> should match
// service_traits::DataType< ::path_planner::PathPlan >
template<>
struct DataType< ::path_planner::PathPlanResponse>
{
  static const char* value()
  {
    return DataType< ::path_planner::PathPlan >::value();
  }
  static const char* value(const ::path_planner::PathPlanResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PATH_PLANNER_MESSAGE_PATHPLAN_H
