// Generated by gencpp from file ros_can_interface/master_navigationMessage.msg
// DO NOT EDIT!


#ifndef ROS_CAN_INTERFACE_MESSAGE_MASTER_NAVIGATIONMESSAGE_H
#define ROS_CAN_INTERFACE_MESSAGE_MASTER_NAVIGATIONMESSAGE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_can_interface
{
template <class ContainerAllocator>
struct master_navigationMessage_
{
  typedef master_navigationMessage_<ContainerAllocator> Type;

  master_navigationMessage_()
    : nav_targetX(0.0)
    , nav_targetY(0.0)
    , nav_targetAngle(0.0)
    , nav_isForward(false)  {
    }
  master_navigationMessage_(const ContainerAllocator& _alloc)
    : nav_targetX(0.0)
    , nav_targetY(0.0)
    , nav_targetAngle(0.0)
    , nav_isForward(false)  {
  (void)_alloc;
    }



   typedef float _nav_targetX_type;
  _nav_targetX_type nav_targetX;

   typedef float _nav_targetY_type;
  _nav_targetY_type nav_targetY;

   typedef float _nav_targetAngle_type;
  _nav_targetAngle_type nav_targetAngle;

   typedef uint8_t _nav_isForward_type;
  _nav_isForward_type nav_isForward;





  typedef boost::shared_ptr< ::ros_can_interface::master_navigationMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_can_interface::master_navigationMessage_<ContainerAllocator> const> ConstPtr;

}; // struct master_navigationMessage_

typedef ::ros_can_interface::master_navigationMessage_<std::allocator<void> > master_navigationMessage;

typedef boost::shared_ptr< ::ros_can_interface::master_navigationMessage > master_navigationMessagePtr;
typedef boost::shared_ptr< ::ros_can_interface::master_navigationMessage const> master_navigationMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_can_interface::master_navigationMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_can_interface::master_navigationMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_can_interface::master_navigationMessage_<ContainerAllocator1> & lhs, const ::ros_can_interface::master_navigationMessage_<ContainerAllocator2> & rhs)
{
  return lhs.nav_targetX == rhs.nav_targetX &&
    lhs.nav_targetY == rhs.nav_targetY &&
    lhs.nav_targetAngle == rhs.nav_targetAngle &&
    lhs.nav_isForward == rhs.nav_isForward;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_can_interface::master_navigationMessage_<ContainerAllocator1> & lhs, const ::ros_can_interface::master_navigationMessage_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_can_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_can_interface::master_navigationMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_can_interface::master_navigationMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_can_interface::master_navigationMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_can_interface::master_navigationMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_can_interface::master_navigationMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_can_interface::master_navigationMessage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_can_interface::master_navigationMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fe1a2421738fe61ce953bf0c9b6e4f00";
  }

  static const char* value(const ::ros_can_interface::master_navigationMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfe1a2421738fe61cULL;
  static const uint64_t static_value2 = 0xe953bf0c9b6e4f00ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_can_interface::master_navigationMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_can_interface/master_navigationMessage";
  }

  static const char* value(const ::ros_can_interface::master_navigationMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_can_interface::master_navigationMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 nav_targetX\n"
"float32 nav_targetY\n"
"float32 nav_targetAngle\n"
"bool nav_isForward\n"
;
  }

  static const char* value(const ::ros_can_interface::master_navigationMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_can_interface::master_navigationMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nav_targetX);
      stream.next(m.nav_targetY);
      stream.next(m.nav_targetAngle);
      stream.next(m.nav_isForward);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct master_navigationMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_can_interface::master_navigationMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_can_interface::master_navigationMessage_<ContainerAllocator>& v)
  {
    s << indent << "nav_targetX: ";
    Printer<float>::stream(s, indent + "  ", v.nav_targetX);
    s << indent << "nav_targetY: ";
    Printer<float>::stream(s, indent + "  ", v.nav_targetY);
    s << indent << "nav_targetAngle: ";
    Printer<float>::stream(s, indent + "  ", v.nav_targetAngle);
    s << indent << "nav_isForward: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.nav_isForward);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_CAN_INTERFACE_MESSAGE_MASTER_NAVIGATIONMESSAGE_H
