(cl:defpackage ros_can_interface-msg
  (:use )
  (:export
   "<LIDAR_STOPSIGNAL>"
   "LIDAR_STOPSIGNAL"
   "<MASTER_ACKNOWLEDGSIGNAL>"
   "MASTER_ACKNOWLEDGSIGNAL"
   "<MASTER_NAVIGATIONMESSAGE>"
   "MASTER_NAVIGATIONMESSAGE"
   "<NAVIGATOR_NAVIGATIONMESSAGE>"
   "NAVIGATOR_NAVIGATIONMESSAGE"
  ))

